[program:docker]
command=/bin/bash -c "service docker start && sleep infinity"
user=root
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/supervisor/docker.log
stderr_logfile=/var/log/supervisor/docker_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
priority=1

[program:mqtt_kafka_bridge]
command=python3 /home/karanw/projects/mqtt_kafka_bridge.py
directory=/home/karanw/projects
user=karanw
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/supervisor/bridge.log
stderr_logfile=/var/log/supervisor/bridge_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
priority=10

[program:kafka_to_postgres]
command=python3 /home/karanw/projects/kafka_to_postgres.py
directory=/home/karanw/projects
user=karanw
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/supervisor/consumer.log
stderr_logfile=/var/log/supervisor/consumer_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
priority=10


[inet_http_server]
port=9001
username=admin
password=<redacted>

[supervisorctl]
serverurl=http://127.0.0.1:9001
username=admin
password=<redacted>
